name: Deploy website

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  deployToTest:
    if: github.event_name == 'pull_request'
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/SaveTheDate-Emailer
            git pull origin ${{ github.head_ref }}

            cd Server
            docker build -t wedding:${{ github.event.number }} .
            docker stop test_wedding || true
            docker rm test_wedding || true
            docker run -d --net=docker_backend --ip=172.20.2.2 --name test_wedding --env-file ../../test.env -v /home/${{ secrets.USERNAME }}/invitations:/usr/src/app/invitations:ro wedding:${{ github.event.number }}

  deployProduction:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/SaveTheDate-Emailer
            git pull origin ${{ github.ref }}

            cd Server
            # Tag the image with the commit hash
            docker build -t wedding:${{ github.sha }} .
            docker stop wedding || true
            docker rm wedding || true
            docker run -d --net=docker_backend --ip=172.20.2.1 --name live_wedding --env-file ../../production.env -v /home/${{ secrets.USERNAME }}/invitations:/usr/src/app/invitations:ro wedding:${{ github.sha }}
