name: PR Review Deployment and Cleanup

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/SaveTheDate-Emailer
          git pull origin ${{ github.head_ref }}
          docker stop pr-preview-${{ github.event.number }} || true
          docker rm pr-preview-${{ github.event.number }} || true
          docker rmi pr-preview:${{ github.event.number }} || true

          cd Server
          docker build -t pr-preview:${{ github.event.number }} .
          docker run -d --net=docker_backend --ip=172.17.1.2 --name pr-preview-${{ github.event.number }} --env-file ../../test.env pr-preview:${{ github.event.number }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          docker stop pr-preview-${{ github.event.number }} || true
          docker rm pr-preview-${{ github.event.number }} || true
          docker rmi pr-preview:${{ github.event.number }} || true
